
OBJS += passes/inject/inject.o
OBJS += passes/inject/inject_fsm.o
OBJS += passes/inject/inject_detect.o
OBJS += passes/inject/inject_extract.o
OBJS += passes/inject/inject_map.o
OBJS += passes/inject/inject_amt.o
OBJS += passes/inject/inject_verify.o
OBJS += passes/inject/inject_expand.o
OBJS += passes/inject/inject_driver.o
OBJS += passes/inject/verify_driver.o
OBJS += passes/inject/create_miter.o
OBJS += passes/inject/verify_miter.o
